# Generated by Django 4.2.3 on 2023-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Yangi'), ('APPROVED', 'Tasdiqlangan'), ('CANCELED', 'Bekor qilingan')], default='PENDING', max_length=32)),
                ('sponsor_type', models.CharField(choices=[('LEGAL_ENTITY', 'Yuridik shaxs'), ('PHYSICAL_PERSON', 'Jismoniy shaxs')], max_length=15)),
                ('full_name', models.CharField(max_length=100)),
                ('balance', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
